-- ตารางผู้ใช้งาน (สำหรับเก็บข้อมูล role ถ้าต้องการขยายระบบ)
-- ในตัวอย่างนี้ role จะถูกจัดการใน session โดยตรงหลัง login
 CREATE TABLE USERS (
     user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
     username VARCHAR2(50) UNIQUE NOT NULL,
     password_hash VARCHAR2(255) NOT NULL, -- ควรเก็บ hash ไม่ใช่ plaintext
     role VARCHAR2(10) NOT NULL -- 'admin' หรือ 'user'
 );