-- ตารางวาระการประชุม (ไฟล์แนบ)
CREATE TABLE AGENDA_ITEMS (
    item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    meeting_id NUMBER NOT NULL,
    item_number NUMBER NOT NULL, -- วาระที่ 1, 2, 3
    original_filename VARCHAR2(255) NOT NULL,
    stored_filename VARCHAR2(255) NOT NULL UNIQUE, -- ชื่อไฟล์ที่เก็บจริงบน server
    file_url VARCHAR2(500) NOT NULL,
    filesize NUMBER,
    CONSTRAINT fk_meeting
        FOREIGN KEY (meeting_id)
        REFERENCES MEETINGS(meeting_id)
        ON DELETE CASCADE -- ถ้าลบ meeting ให้ลบ agenda items ด้วย
);